sylius_grid:
  grids:
    vldmrk_admin_what_in_box:
      driver:
        name: doctrine/orm
        options:
          class: "%vldmrk.model.what_in_box.class%"
          repository:
            method: createQueryBuilderByProductId
            arguments: ["%locale%", $productId]
      sorting:
        position: asc
      fields:
        code:
          type: string
          label: sylius.ui.code
          sortable: ~
        title:
          type: string
          label: sylius.ui.title
          sortable: title
        image:
          type: twig
          label: sylius.ui.image
          path: .
          options:
            template: "@VldmrkSyliusWhatInBoxPlugin/Admin/Grid/Field/_image.html.twig"
        position:
          type: twig
          label: sylius.ui.position
          path: .
          sortable: position
          options:
            template: "@VldmrkSyliusWhatInBoxPlugin/Admin/Grid/Field/_position.html.twig"
      filters:
        code:
          type: string
          label: sylius.ui.code
        title:
          type: string
          label: sylius.ui.title
      actions:
        main:
          update_positions:
            type: update_what_in_box_positions
            options:
              productId: $productId
          create:
            type: create
            options:
              link:
                parameters: { productId: $productId }

        item:
          update:
            type: update
            options:
              link:
                parameters:
                  id: resource.id
                  productId: $productId
          delete:
            type: delete
            options:
              link:
                parameters:
                  id: resource.id
                  productId: $productId
