services:
  vldmrk.form.type.what_in_box:
    class: Vldmrk\SyliusWhatInBoxPlugin\Form\Type\WhatInBoxType
    arguments:
      - '%vldmrk.model.what_in_box.class%'
      - '%vldmrk.form.type.what_in_box.validation_groups%'
    tags:
      - { name: form.type }
