# config/resources.yaml
sylius_resource:
  resources:
    vldmrk.what_in_box:
      driver: doctrine/orm # You can use also different driver here
      classes:
        controller: Vldmrk\SyliusWhatInBoxPlugin\Controller\WhatInBoxController
        model: Vldmrk\SyliusWhatInBoxPlugin\Entity\WhatInBox
        repository: Vldmrk\SyliusWhatInBoxPlugin\Repository\WhatInBoxRepository
        factory: Vldmrk\SyliusWhatInBoxPlugin\Factory\WhatInBoxFactory
        form: Vldmrk\SyliusWhatInBoxPlugin\Form\Type\WhatInBoxType
      translation:
        classes:
          model: Vldmrk\SyliusWhatInBoxPlugin\Entity\WhatInBoxTranslation

    vldmrk.what_in_box_image:
      driver: doctrine/orm
      classes:
        model: Vldmrk\SyliusWhatInBoxPlugin\Entity\WhatInBoxImage
