vldmrk_admin_what_in_box:
  resource: |
    alias: vldmrk.what_in_box
    section: admin
    templates: "@SyliusAdmin\\Crud"
    except: ['show', 'delete']
    redirect: index
    grid: vldmrk_admin_what_in_box
    permission: true
    vars:
        all:
            subheader: sylius.ui.manage_languages_available_in_the_store
            templates:
                form: "@VldmrkSyliusWhatInBoxPlugin/_form.html.twig"
        index:
            icon: translate
  type: sylius.resource

vldmrk_admin_ajax_product_what_in_box_update_position:
    path: /update
    methods: [PUT]
    defaults:
      _controller: vldmrk.controller.what_in_box:updatePositionsAction
      _format: json
      _sylius:
        permission: true

vldmrk_admin_what_in_box_index:
  path: /
  methods: [GET]
  defaults:
    _controller: vldmrk.controller.what_in_box:indexAction
    _sylius:
      template: "@SyliusAdmin/Crud/index.html.twig"
      grid: vldmrk_admin_what_in_box
      section: admin
      permission: true
      vars:
        route:
          parameters:
            productId: $productId
        templates:
          breadcrumb: "@VldmrkSyliusWhatInBoxPlugin/Admin/Index/_breadcrumb.html.twig"
        icon: cubes
        subheader: vldmrk.ui.manage_what_in_box
        product: expr:notFoundOnNull(service('sylius.repository.product').find($productId))

vldmrk_admin_what_in_box_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: vldmrk.controller.what_in_box:createAction
    _sylius:
      factory:
        method: createForProduct
        arguments:
          - expr:notFoundOnNull(service('sylius.repository.product').find($productId))
      template: "@SyliusAdmin/Crud/create.html.twig"
      section: admin
      redirect:
        route: vldmrk_admin_what_in_box_index
        parameters: { productId: $productId }
      permission: true
      vars:
        route:
          parameters:
            productId: $productId
        templates:
          form: "@VldmrkSyliusWhatInBoxPlugin/Admin/_form.html.twig"
          breadcrumb: "@VldmrkSyliusWhatInBoxPlugin/Admin/Create/_breadcrumb.html.twig"
          #header_title: "@SyliusAdmin/ProductVariant/Create/_headerTitle.html.twig"

vldmrk_admin_what_in_box_update:
  path: /{id}/edit
  methods: [GET, PUT]
  defaults:
    _controller: vldmrk.controller.what_in_box:updateAction
    _sylius:
      #template: "@SyliusAdmin/Crud/update.html.twig"
      grid: vldmrk_admin_what_in_box
      section: admin
      redirect:
        route: vldmrk_admin_what_in_box_index
        parameters: { productId: $productId }
      permission: true
      repository:
        method: findOneByIdAndProductId
        arguments:
          id: $id
          productId: $productId
      template: "@SyliusAdmin/Crud/update.html.twig"
      vars:
        route:
          parameters:
            id: $id
            productId: $productId
        templates:
          form: "@VldmrkSyliusWhatInBoxPlugin/Admin/_form.html.twig"
          breadcrumb: "@VldmrkSyliusWhatInBoxPlugin/Admin/Update/_breadcrumb.html.twig"
          #toolbar: "@SyliusAdmin/ProductVariant/Update/_toolbar.html.twig"


vldmrk_admin_what_in_box_delete:
  path: /{id}
  methods: [DELETE]
  defaults:
    _controller: vldmrk.controller.what_in_box:deleteAction
    _sylius:
      section: admin
      redirect: referer
      permission: true
      repository:
        method: findOneByIdAndProductId
        arguments:
          id: $id
          productId: $productId
